# Generated by Django 4.2.17 on 2024-12-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название модели')),
                ('image', models.URLField(verbose_name='Изображение')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('lte_exists', models.BooleanField(verbose_name='Наличие LTE')),
                ('slug', models.SlugField(max_length=30, unique=True, verbose_name='URL')),
            ],
        ),
    ]
